projects/scrapper/basic_prj/urls.py
from django.conf.urls import include, url
#from django.conf.urls.defaults import *
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sample_app/', include('sample_app.urls', namespace='sample_app')),
    #url(r'^sample_app/', include("smaple_app.urls", namespace="sample_app")),
]

#urlpatterns = patterns( '',
#    url(r'^sample_app/', include('smaple_app.urls', namespace="sample_app")),
#    url(r'^admin/', admin.site.urls),
#)

projects/scrapper/sample_app/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from sample_app import views
from sample_app.views import VideoUrlUpdateView, VideoUpdateView, VideoUrlCategoryUpdateView

#app_name = 'sample_app'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^write/$', views.write, name='write'),
    url(r'^write_ok/$', views.write_ok, name='write_ok'),
    url(r'^show_vlist/$', views.show_vlist, name='show_vlist'),
    url(r'^modify/$', views.modify, name='modify'),
    url(r'^modify_ok/$', views.modify_ok, name='modify_ok'),
    # Category 사용하는 url pattern
    url(r'^(?P<pk>[0-9]+)/edit/$', VideoUrlCategoryUpdateView.as_view(), name='edit'),
    # Category 사용하지 않는 url pattern, UpdateView 클래스 사용
    url(r'^(?P<pk>[0-9]+)/update/$', VideoUrlUpdateView.as_view(), name='update'),
    # View 클래스 이용
    url(r'^(?P<pk>[0-9]+)/mupdate/$', VideoUpdateView.as_view(), name='mupdate'),
]

projects/scrapper/sample_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# Create your models here.
class VideoCategory(models.Model):
    category = models.CharField(max_length=20)
    # pub_date = models.DateTimeField('date published') # 추후 다시 추가

    def __unicode__(self):
        return self.category


class VideoUrl(models.Model):
    category = models.ForeignKey(VideoCategory, verbose_name=u"카테고리",
                                 on_delete=models.CASCADE, default=None)
    vod_id = models.AutoField(primary_key=True)
    subject = models.CharField(max_length=50)
    url = models.CharField(max_length=100)
    description = models.CharField(max_length=400)
    # pub_date = models.DateTimeField('date published') # 추후 다시 추가

    def __unicode__(self):
        return self.subject

projects/scrapper/sample_app/forms.py
from django import forms
from .models import VideoUrl
from django.forms import ModelForm


class VideoForm(ModelForm):
    subject = forms.CharField(label='VOD Name',
                              max_length=100,
                              widget=forms.TextInput(attrs={'class': 'form-control'}))

    url = forms.CharField(label='url',
                          max_length=500,
                          widget=forms.TextInput(attrs={'class': 'form-control'}))

    description = forms.CharField(label='comment',
                                  max_length=500,
                                  widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = VideoUrl
        fields = ('subject', 'url', 'description', 'vod_id',)
        # video_subject = forms.CharField(label='VOD Name', max_length=100)
        # video_url = forms.CharField(label='url', max_length=500)
        # video_comment = forms.CharField(label='comment', max_length=500)


class VideoMetaForm(ModelForm):
    class Meta:
        model = VideoUrl
        fields = ('subject', 'url', 'description', 'vod_id', 'category')
        # exclude = ['category']

projects/scrapper/sample_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http.response import Http404
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect

from sample_app.forms import VideoMetaForm
from sample_app.models import VideoUrl, VideoCategory
# from .VideoForm import VideoForm
from forms import VideoForm
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import UpdateView
from django.views.generic import View
from django.core.urlresolvers import reverse_lazy
from pprint import pprint


# Create your views here.
def index(request):
    template_data = {}
    return render(request, 'sample_app/index.html', template_data)


def write(request):
    categories = VideoCategory.objects.all()
    template_data = {
        'categories': categories
    }
    return render(request, 'sample_app/write.html', template_data)


def write_ok(request):
    post = request.POST
    template_data = {}
    m_subject = post['subject']
    m_url = post['url']
    m_description = post['description']
    category_id = int(post['cid'].encode('utf-8'))

    m_category = VideoCategory.objects.get(pk=category_id)
    v = VideoUrl(subject=m_subject, url=m_url, description=m_description, category=m_category)
    v.save()
    return HttpResponseRedirect(reverse('sample_app:show_vlist'), template_data)


def show_vlist(request):
    video_list = VideoUrl.objects.all()
    msg = {'video_list': video_list}
    return render(request, 'sample_app/show_vlist.html', msg)


def modify(request):
    if request.method == 'GET':
        vod = VideoUrl.objects.get(vod_id=request.GET['vod_id'])
        return render(request, 'sample_app/modify.html', {'vod': vod})
    elif request.method == 'POST':
        # 참고 URL : https://docs.djangoproject.com/en/1.11/topics/forms/modelforms/#the-save-method
        # 1) Form 클래스로 구현
        # modify 페이지 자체를 Form클래스로 구현할때의 페이지 구성, POST방식

        # vod_id에 대한 하나의 데이터(로우) 얻어오기
        vod = VideoUrl.objects.get(vod_id=request.POST['vod_id'])

        # 하나의 로우는 model instance라고 하는가보다. instance 값으로 model 데이터를 넘겨준다.
        form = VideoForm(instance=vod)
        ctx = {
            'form': form
        }

        # form데이터를 실어서 modify.html로 전송
        return render(request, 'sample_app/modify.html', ctx)


def modify_ok(request):
    if request.method=='POST':
        # 단순 저장이 아닌 update구문으로 변경할 것
        # 원인) 단순 저장할 경우 복사본 데이터가 생성된다.
        # 방법) Model instance를 얻어온 후 해당 값들을 업데이트 해주는 수밖에.
        form = VideoForm(request.POST)
        if form.is_valid():
            vod = VideoUrl.objects.get(pk=request.POST['vod_id'])
            # vod.objects.update(force_update=True)
            # VideoUrl.objects.update(force_update=True)
            return render(request, 'sample_app/show_vlist.html', {'form' : form })
    return render(request, 'sample_app/show_vlist.html')


class VideoUrlCategoryUpdateView(UpdateView):
    form_class = VideoForm
    template_name = 'sample_app/edit.html'

    def get(self, request, pk):
        vod = VideoUrl.objects.get(vod_id=pk)
        template_data = {
            'categories': VideoCategory.objects.all(),
            'selected': vod.category,
            'vod_id': vod.vod_id,
            'subject': vod.subject,
            'url': vod.url,
            'description': vod.description
        }

        return render(request, self.template_name, template_data)

    def post(self, request, **kwargs):
        post = request.POST.copy()

        category = VideoCategory.objects.get(pk=post['category'])
        video = VideoUrl.objects.get(pk=int(post['vod_id']))
        video.category = category

        form = VideoMetaForm(post, instance=video)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('sample_app:show_vlist'), {})
        else:
            raise Http404


# UpdateView 클래스 상속받아 사용하는 방식 ( UpdateView : Form을 자동적으로 사용하는 클래스 )
class VideoUrlUpdateView(UpdateView):
    form_class = VideoForm
    template_name = 'sample_app/videourl_form.html'

    def get(self, request, pk):
        # https://tutorial.djangogirls.org/ko/django_forms/#폼-수정하기
        vod = VideoUrl.objects.get(vod_id=pk)
        # vod 객체를 form 객체로 변환
        form = self.form_class(instance=vod)
        # 직접 생성자를 사용해도 된다
        # form = VideoForm(instance=vod)

        return render(request, self.template_name, {'form': form})

    def post(self, request, pk, **kwargs):
        # 참고자료 : http://ruaa.me/django-view/
        # 구글 검색어 : generic view post
        form = self.form_class(request.POST)

        # 1) pk값에 해당하는 vod 객체 얻어온다.
        vod = VideoUrl.objects.get(vod_id = pk)

        # 2) vod객체에 POST로 전달받은 form 값을 저장한다.
        VideoUrl.objects.filter(pk=pk).update(subject=request.POST['subject'],
                                              description=request.POST['description'],
                                              url=request.POST['url'])

        if form.is_valid():
            return HttpResponseRedirect(reverse('sample_app:show_vlist'), {'test': 'test'})
        return render(request, self.template_name, {'form': form})


# ModelForm 사용하는 방식
class VideoUpdateView(View):
    form_class = VideoForm
    template_name = 'sample_app/videourl_form.html'

    def get(self, request, pk):
        vod = VideoUrl.objects.get(vod_id=pk)
        return render(request, self.template_name, {'form': vod})

    def post(self, request, *args):
        form = self.form_class(request.POST)
        # if form.is_valid():
        #     return HttpResponseRedirect('sample_app:show_vlist')
        return render(request, self.template_name, {'form': form}) # form이 유효하지 않을때. 에러가 있을경우

projects/scrapper/sample_app/templates/sample_app/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> Modify Content </title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container" style="width:400px; padding:15px">
        <h1> Edit URL Information </h1>
    </div>

    <div class="container panel panel-default">
        <form action="." method="post">{% csrf_token %}
        <table class="table table-bordered">
            <thead></thead>
            <tbody>
                <tr>
                    <td><p>title </p></td>
                    <td><input class="form-control" type="text" name="subject" value="{{ subject }}"/></td>
                </tr>
                <tr>
                    <td><p>category </p></td>
                    <td>
                        <select name="category">
                            {% for category in categories %}
                                {% if selected == category %}
                                    <option value="{{ category.pk }}" selected="selected">{{ category.category }}</option>
                                {% else %}
                                    <option value="{{ category.pk }}" >{{ category.category }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </td>
                </tr>
                <tr>
                    <td><p>url </p></td>
                    <td><input class="form-control" type="text" name="url" value="{{ url }}"/></td>
                </tr>
                <tr>
                    <td><p>description </p></td>
                    <td><input class="form-control" type="text" name="description" value="{{ description }}"/></td>
                </tr>
                <tr>
{#                    <td><input class="form-control" type="hidden" name="category" value="Videos"/></td>#}
                    <td><input type="hidden" name="vod_id" value="{{ vod_id }}" class="btn btn-default"/></td>
                    <td colspan="2"><input type="submit"/></td>
                </tr>
            </tbody>
        </table>
        </form>
    </div>


</body>
</html>

projects/scrapper/sample_app/templates/sample_app/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1-strict.dtd">
<html lang="ko">
    <head> 
        <title> WELCOME </title>
        <!-- 합쳐지고 최소화된 최신 CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        
        <!-- 부가적인 테마 -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
        
        <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    </head>
    
    <body>
        <div class="header container" style="width:400px; padding:15px">
            <h1> Youtube Scrap APP </h1>
        </div>
        <div class="list-group container" style="width:400px;padding:15px;">
            <a href="/sample_app/write/" class="list-group-item active"> +add URLs</a>
            <a href="/sample_app/show_vlist/" class="list-group-item"> show list
{#                <span class="badge">14</span>#}
            </a>
        </div>
    </body>
</html>

projects/scrapper/sample_app/templates/sample_app/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      VIDEO LIST
    </title>
</head>
<body>
  <form action="{% url 'sample_app:write_ok'%}" method="post">{% csrf_token %}
  <table>
    <tr>
      <td><p>title : </p></td>
      <td><input type="text" name="subject"/></td>
    </tr>
    <tr>
      <td><p>url : </p></td>
      <td><input type="text" name="url"/></td>
    </tr>
    <tr>
      <td><p>description : </p></td>
      <td><input type="text" name="description"/></td>
    </tr>
    <tr>
      <td><input type="hidden" name="category" value="Videos"/></td>
      <td colspan="2"><input type="submit" name="저장" /></td>
    </tr>
  </table>
  </form>
</body>
</html>

projects/scrapper/sample_app/templates/sample_app/modify.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> modify URLs </title>
</head>
<body>
{% csrf_token %}
<h1> --- EDIT SINGLE PAGE --- </h1>
{#<form action="{% url 'sample_app:modify_ok' %}" method="post">#}
    <form method="post" action="{% url 'sample_app:modify_ok' %}">
    {% csrf_token %}
    {{ form.as_p }}
{#    form 객체값을 어떤방식으로 html로 받아오는지 알아볼 것 #}
{#    <table>#}
{#        <tr>#}
{#            <td><p>제목 : </p></td>#}
{#            <td><input type="text" name="subject" value="{{vod.subject}}"/></td>#}
{#        </tr>#}
{#        <tr>#}
{#            <td><p>URL : </p></td>#}
{#            <td><input type="text" name="url" value="{{vod.url}}"/></td>#}
{#        </tr>#}
{#        <tr>#}
{#            <td><p>설명 : </p></td>#}
{#            <td><input type="text" name="description" value="{{vod.description}}"/></td>#}
{#        </tr>#}
{#        <tr>#}
{#            <td><input type="hidden" name="vod_id" value="{{vod.vod_id}}"/></td>#}
{#            <td><input type="submit" value="Save"/></td>#}
{#        </tr>#}
{#    </table>#}
    <p>
        <input type="submit" value="Save">
    </p>
    </form>
{#    <input type="text" name="subject" value="{{vod.subject}}"/>#}
{#</form>#}
{#    <form method="POST">#}
{#        <button type="submit"> 저장 </button>#}
{#    </form>#}
</body>
</html>

projects/scrapper/sample_app/templates/sample_app/show_list.html
<html>
 <head>
   <title>show list of videos</title>
 </head>
 <body>
   <h1> list of video urls  </h1>
   <table>
       {% for vod in video_list %}
           <tr>
                <td><a href="{{ vod.url }}"> {{ vod.subject }}</a></td>
                <td>
                    <a href="{% url 'sample_app:update' vod.vod_id %}"> Edit </a>
                </td>
{#           "{% url 'sample_app:write_ok'%}"#}
           </tr>
{#           <tr>#}
{#                <td colspan="2">{{ vod. }}</td>#}
{#           </tr>#}
       {% endfor %}
   </table>
 </body>
</html>
{# modify하는 html로 넘어가는 버튼 기능 구현, url설계, modify()함수를 views.py에 구현 #}

projects/scrapper/sample_app/templates/sample_app/show_vlist.html
<html>
 <head>
   <title>show list of videos</title>
     <!-- 합쳐지고 최소화된 최신 CSS -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
     <!-- 부가적인 테마 -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
     <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

     <style>
             .subject{
                font-size: 2em;
                text-align: center;
            }
            .edit{
                float: right;
{#                height: 20%;#}
                vertical-align: center;
            }
            .empty{
                margin:2px;
            }
        </style>
 </head>
 <body>
    <div class="container-fluid panel panenl-default" style="width:400px; padding:15px">
        <div class="title">
            <span class="subject"> <b>Video List</b> </span>
            <a href="/sample_app/index/" class="btn btn-default edit" role="button" > Go Home </a>
        </div>
    </div>
    <div class="empty">
        <hr/>
    </div>
    <div class="container">
        <div class="row">
            {% for vod in video_list %}
                <div class="col-sm-6 col-md-4 panel panel-default">
                    <div class="thumbnail embed-responsive embed-responsive-16by9" width="330" height="220">
<!--                    <div class="thumbnail">-->
<!--                        <img src="..." alt="...">-->
                        <iframe width="310" height="200" src="{{ vod.url }}" frameborder="0" class="media-object"></iframe>
                    </div>
                    <div class="caption">
                        <h3> {{ vod.subject }} </h3>
                        <p> {{ vod.description }} </p>
                        <p>
                            <!-- 카테고리 사용하지 않는 페이지 URL -->
{#                            <a href="{% url 'sample_app:update' vod.vod_id %}" class="btn btn-default" role="button">Edit</a>#}
                            <!-- 카테고리 사용하는 수정 페이지 URL -->
                            <a href="{% url 'sample_app:edit' vod.vod_id %}" class="btn btn-default" role="button">Edit</a>
                        </p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
 </body>
</html>

projects/scrapper/sample_app/templates/sample_app/videourl_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> Modify Content </title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container" style="width:400px; padding:15px">
        <h1> Edit URL Information </h1>
    </div>

    <div class="container panel panenl-default">
        <table class="table table-bordered">
            <thead></thead>
            <tbody>
                <form action="." method="post">{% csrf_token %}
                    {% if form.errors %}
                        <p class="errornote"> Wrong! Please correct the error(s) below. </p>
                    {% endif %}
                    {{ form.as_p }}

                    <input type="hidden" value="{{ form.vod_id }}" class="btn btn-default"/>
                    <input type="submit" value="submit" class="btn btn-default"/>
                </form>
            </tbody>
        </table>
    </div>
</body>
</html>

projects/scrapper/sample_app/templates/sample_app/write.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> Write Youtube URL </title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container" style="width:400px; padding:15px">
        <h1> Write URL Information </h1>
    </div>

    <div class="container panel panenl-default">
        <form action="{% url 'sample_app:write_ok'%}" method="post">{% csrf_token %}
            <table class="table table-bordered table-responsive">
                <tr>
                    <td><p>title </p></td>
                    <td><input type="text" name="subject" class="form-control"/></td>
                </tr>
                <tr class="rowlink">
                    <td><p>category </p></td>
{#                    <td>#}
{#                        <div class="btn-group">#}
{#                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">#}
{#                                Action <span class="caret"></span>#}
{#                            </button>#}
{#                            <ul class="dropdown-menu" role="menu">#}
{#                                <li><a href="#">Action</a></li>#}
{#                                <li><a href="#">Another action</a></li>#}
{#                                <li><a href="#">Something else here</a></li>#}
{#                                <li class="divider"></li>#}
{#                                <li><a href="#">Separated link</a></li>#}
{#                            </ul>#}
{#                        </div>#}
{#                    </td>#}
                    <td>
                        <select name="cid">
                            {% for category in categories %}
                                <option value="{{ category.pk }}">{{ category.category }}</option>
                            {% endfor %}
                        </select>
                    </td>
                </tr>
                <tr>
                    <td><p>url </p></td>
                    <td><input type="text" name="url" class="form-control"/></td>
                </tr>
                <tr>
                    <td><p>description </p></td>
                    <td><input type="text" name="description" class="form-control"/></td>
                </tr>
                <tr>
                    <td><input type="hidden" name="category" value="Videos"/></td>
                    <td colspan="2"><input type="submit" name="저장" /></td>
                </tr>
            </table>
        </form>
    </div>
</body>
</html>

projects/scrapper/sample_app/templates/sample_app/write_ok.html
<html>
</html>